http://localhost:3001/books

###

http://localhost:3001/unknown

###

GET http://localhost:3001/books?email=IamAJ@gmail.com HTTP/1.1
content-type: application/json


###
POST http://localhost:3001/books?email=basseuph@gmail.com HTTP/1.1
content-type: application/json

{
    "name": "new book",
    "description": "new book description",
    "status": "new book status"
}

###

DELETE http://localhost:27017/books HTTP/1.1